apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: x4vcih49l-python 
  janus-idp.io/tekton: x4vcih49l-python
  backstage.io/kubernetes-id: x4vcih49l-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: x4vcih49l-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml